// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransferRoom.POC.EPL.SquadApi.Data;

#nullable disable

namespace TransferRoom.POC.EPL.SquadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250624113539_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.Squad", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.TeamNickname", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "Nickname");

                    b.ToTable("Nicknames");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.Squad", b =>
                {
                    b.HasOne("TransferRoom.POC.EPL.SquadApi.Models.Player", "Player")
                        .WithMany("Squads")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransferRoom.POC.EPL.SquadApi.Models.Team", "Team")
                        .WithMany("Squads")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.TeamNickname", b =>
                {
                    b.HasOne("TransferRoom.POC.EPL.SquadApi.Models.Team", "Team")
                        .WithMany("Nicknames")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.Player", b =>
                {
                    b.Navigation("Squads");
                });

            modelBuilder.Entity("TransferRoom.POC.EPL.SquadApi.Models.Team", b =>
                {
                    b.Navigation("Nicknames");

                    b.Navigation("Squads");
                });
#pragma warning restore 612, 618
        }
    }
}
