name: Backend CI

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./backend/TransferRoom.POC.EPL.SquadApi.sln

      - name: Build
        run: dotnet build ./backend/TransferRoom.POC.EPL.SquadApi.sln --no-restore --configuration Release

      - name: Publish
        run: dotnet publish ./backend/TransferRoom.POC.EPL.SquadApi.sln --configuration Release --output ./backend/publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-publish
          path: ./backend/publish
